### ISSUE TITLE
fastq screen wrapper

### ISSUE THREAD

**Issue by jfear** [lcdb/lcdb-wrapper-tests#32]
I had started working on a fastq screen wrapper based on the one from lcdb-workflows. I am debating how to pass references to fastq screen. Currently you have a dictionary that you pass, but I am thinking instead of passing an entire dictionary it would be better to pass via the `input` dict. 

Any thoughts?

**Comment by daler** [comment]
Filenames should prob go in the input dict to trigger index building. But I think there are non-filename params in that dict, so they would have to go in params.

**Comment by jfear** [comment]
Added PR #36
