### ISSUE TITLE
temporarily use custom repo

### ISSUE THREAD

**Issue by jfear** [lcdb/lcdb-wrapper-tests#34]
How do you think we should handle upstream packages that have been updated but not pushed. 

For example, my patch to snakemake fixing relative paths with wrappers has been merged into upstream, but Johannes has not packaged a new version (3.10.1). In my patch I implement using urllib's way of dealing with relative paths, I updated the wrappers, but the tests will fail because the change is no backwards compatible. 

I am sure this is a common problem with a few possible solutions.

* ping Johannes and ask him to release a new version with the current master
* package dev and push to our lcdb conda channel
* patch travis to install from master
* wait

Do you have a prefer/suggested method? I think I would lean towards pushing a dev package to the lcdb conda channel.  Don't really want to bug Johannes because he is busy enough and patching the travis code seem error prone.

**Comment by daler** [comment]
Agreed, dev package to lcdblib is probably best. I would make the version numbers reflect this, e.g., https://www.python.org/dev/peps/pep-0440/#id35, so that we can keep both bioconda and lcdblib channels activated and not get confused about which channel the dependency is coming from.

**Comment by jfear** [comment]
Yep I think this is the best option.
